project_recipe/urls.py
from django.contrib import admin
from django.urls import path
from app_recipe.views import *
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', MainView.as_view(), name='index'),
    path('add_ingredient/', AddIngredientView.as_view(), name='add_ingredient'),
    path('add_recipe/', AddRecipeView.as_view(), name='add_recipe'),
    path('add_unit/', AddUnitView.as_view(), name='add_unit'),
    path('recipe/<int:recipe_id>/', RecipeByIdView.as_view(), name='recipe_by-id'),

    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('add_user/', AddUserView.as_view(), name='add_user'),
    path('reset_password/<int:user_id>', ChangePasswordView.as_view(), name='reset_password'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_recipe/models.py
from django.db import models

# Create your models here.

class Ingredient(models.Model):
    ingredient_name = models.CharField(max_length=128)
    calories = models.IntegerField(null=True)


class Unit(models.Model):
    unit_name = models.CharField(max_length=64)


class Category(models.Model):  # while skipping
    category_name = models.CharField(max_length=64)


class Cuisine(models.Model):  # while skipping
    cuisine_name = models.CharField(max_length=64)


class Recipe(models.Model):
    # author = models.CharField(max_length=128)
    recipe_name = models.CharField(max_length=128)
    main_image = models.ImageField(upload_to='images/', blank=True, null=True)
    ingredients = models.ManyToManyField(Ingredient, through="RecipeIngredientQuantityUnit")
    # quantity = models.IntegerField(null=True)  # redirected to model RecipeIngredientQuantityUnit
    # units = models.ForeignKey(Unit, on_delete=models.CASCADE, null=True)  # redirected to model RecipeIngredientQuantityUnit
    cooking_time = models.TimeField(null=True)
    number_of_persons = models.IntegerField(null=True)
    categories = models.ManyToManyField(Category)  # while skipping
    cuisines = models.ManyToManyField(Cuisine)  # while skipping
    recipe_date = models.DateTimeField(auto_now_add=True, null=True)
    rating = models.IntegerField(default=0)
    # steps = models.ForeignKey(Step, on_delete=models.CASCADE, null=True)


class RecipeIngredientQuantityUnit(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    quantity = models.DecimalField(max_digits=6, decimal_places=2, null=True)
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE)


class Step(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    # step_number = models.IntegerField()
    description = models.TextField()
    step_image = models.ImageField(upload_to='images/', blank=True, null=True)

    class Meta:
        permissions = (
            ("change_password", 'Can change password'),
        )


# class Comment(models.Model):
#     from_user = models.ForeignKey(User, on_delete=models.CASCADE)  # в какой класс??
#     to_recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
#     comment_content = models.TextField()
#     comment_date = models.DateTimeField(auto_now_add=True)


# class Rating(models.Model):
#     rating_points = models.IntegerField()
#     users = models.ForeignKey(User, on_delete=models.CASCADE)
#     recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)

app_recipe/forms.py
from django import forms
from django.contrib.auth.models import User
from prompt_toolkit.validation import ValidationError

from .models import *


class AddRecipeForm(forms.Form):
    recipe_name = forms.CharField(max_length=128)

    main_image = forms.ImageField(required=False)

    cooking_time = forms.TimeField(widget=forms.TimeInput)

    number_of_persons = forms.IntegerField()

    ingredients_object = Ingredient.objects.all()
    ingredients_choises = [(ingredd.ingredient_name, ingredd.ingredient_name) for ingredd in ingredients_object]
    ingredients = forms.ChoiceField(choices=ingredients_choises)

    quantity = forms.DecimalField(min_value=0.01, max_digits=6, decimal_places=2)

    units_object = Unit.objects.all()
    units_choises = [(unit.unit_name, unit.unit_name) for unit in units_object]
    units = forms.ChoiceField(choices=units_choises)

    step_description = forms.CharField(widget=forms.Textarea)

    step_image = forms.ImageField(required=False)


class LoginForm(forms.Form):
    login = forms.CharField(label='Login', max_length=120)
    password = forms.CharField(label='Password', max_length=120, widget=forms.PasswordInput)


def LoginCheck(value):
    is_user_in_DB = User.objects.filter(username=value)
    if len(is_user_in_DB) > 0:
        raise ValidationError('Użytkownik już istneje')


class AddUserForm(forms.Form):
    login = forms.CharField(max_length=20, validators=[LoginCheck])
    password = forms.CharField(max_length=16, widget=forms.PasswordInput())
    repeated_password = forms.CharField(max_length=16, widget=forms.PasswordInput())
    email = forms.EmailField()

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        repeated_password = cleaned_data.get('repeated_password')
        if password != repeated_password:
            raise forms.ValidationError('Hasła są różne!')


class ChangePasswordForm(forms.Form):
    new_password1 = forms.CharField(label='Password', max_length=16, widget=forms.PasswordInput())
    new_password2 = forms.CharField(label='Repeat password', max_length=16, widget=forms.PasswordInput())

    def clean(self):
        cleaned_data = super().clean()
        new_password1 = cleaned_data.get('new_password1')
        new_password2 = cleaned_data.get('new_password2')
        if new_password1 != new_password2:
            raise forms.ValidationError('Hasła są różne!')

app_recipe/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from django.views.generic import CreateView
from django.urls import reverse_lazy
from app_recipe.forms import *
from app_recipe.models import *
from app_recipe.voice import start_voice_assistant
import threading


class MainView(View):
    def get(self, request):
        all_recipes = Recipe.objects.all().order_by('-pk')[:3]
        return render(request, 'app_recipe/index.html', {'recipes':all_recipes})


class AddIngredientView(CreateView):
    model = Ingredient
    fields = ['ingredient_name', 'calories']
    success_url = reverse_lazy('index')


class AddUnitView(CreateView):
    model = Unit
    fields = ['unit_name']
    success_url = reverse_lazy('index')


class AddRecipeView(PermissionRequiredMixin, View):
    permission_required = 'app_recipe.add_recipe'

    def get(self, request):
        form = AddRecipeForm()
        return render(request, 'app_recipe/add_recipe.html', {'form':form, 'submit_value':'Dodaj przepis'})

    def post(self, request):
        form = AddRecipeForm(request.POST, request.FILES)

        if form.is_valid():

            # constant_block
            name = form.cleaned_data['recipe_name']
            main_image = form.cleaned_data['main_image']
            cooking_time = form.cleaned_data['cooking_time']
            number_of_persons = form.cleaned_data['number_of_persons']

            # ingredients_block, all in arrays
            ingredients = request.POST.getlist('ingredients')
            quantity = request.POST.getlist('quantity')
            units = request.POST.getlist('units')

            # steps block, all in arrays
            description = request.POST.getlist('step_description')
            step_image = request.FILES.getlist('step_image')

            # arrays of objects from DB
            ingredients_array = [Ingredient.objects.get(ingredient_name=ingredient) for ingredient in ingredients]
            unit_array = [Unit.objects.get(unit_name=unit) for unit in units]

            recipe_object = Recipe.objects.create(recipe_name=name, main_image=main_image,
                                                  cooking_time=cooking_time, number_of_persons=number_of_persons)
            # add ingredients to DB
            for index, ingredient in enumerate(ingredients_array):
                recipe_ingredient_quantity_unit_object = RecipeIngredientQuantityUnit()
                recipe_ingredient_quantity_unit_object.recipe = recipe_object
                recipe_ingredient_quantity_unit_object.ingredient = ingredient
                recipe_ingredient_quantity_unit_object.quantity = quantity[index]
                recipe_ingredient_quantity_unit_object.unit = unit_array[index]
                recipe_ingredient_quantity_unit_object.save()

            # add steps to DB
            for index in range(len(description)):
                Step.objects.create(recipe=recipe_object, description=description[index],
                                    step_image=step_image[index])

            return redirect("index")

        return render(request, 'app_recipe/add_recipe.html', {'form':form})


class RecipeByIdView(View):
    def get(self, request, recipe_id):
        recipe_obj = get_object_or_404(Recipe, pk=recipe_id)
        array_steps_to_voice = [element.description for element in recipe_obj.step_set.all().order_by('pk')]
        try:
            print('Try to ON mic')
            asynch_process = threading.Thread(target=start_voice_assistant, args=(array_steps_to_voice,))
            asynch_process.start()
        finally:
            print('all errors after voice')
        print('after asynch process')
        return render(request, 'app_recipe/recipe_by_id.html', {'recipe_obj': recipe_obj})


# Empty -------------------------------------------------------!!!!!
class allRecipesView(View):
    def get(self, request):
        pass
# --------------------------------------------------------------

class LoginView(View):
    def get(self, request):
        form = LoginForm()
        return render(request, 'app_recipe/form.html', {'form': form, 'submit_value':'Login'})

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['login']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("index")
            else:
                return render(request, 'app_recipe/form.html', {'form': form, 'info': 'Błędny login lub hasło', 'submit_value':'Login'})
        else:
            return render(request, 'app_recipe/form.html', {'form': form})

class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect('index')


class AddUserView(View):
    def get(self, request):
        form = AddUserForm()
        return render(request, 'app_recipe/form.html', {'form':form})

    def post(self, request):
        form = AddUserForm(request.POST)

        if form.is_valid():
            users_login = form.cleaned_data['login']
            first_password = form.cleaned_data['password']
            email = form.cleaned_data['email']

            new_user = User(username=users_login, email=email)
            new_user.set_password(first_password)
            new_user.save()
            return redirect('index')

        else:
            return render(request, 'app_recipe/form.html', {'form': form})


class ChangePasswordView(PermissionRequiredMixin, View):
    permission_required = 'app_recipe.change_password'

    def get(self, request, user_id):
        form = ChangePasswordForm
        return render(request, 'app_recipe/form.html', {'form': form})

    def post(self, request, user_id):
        form = ChangePasswordForm(request.POST)
        user = get_object_or_404(User, pk=user_id)
        if form.is_valid():
            new_password = form.cleaned_data['new_password1']
            user.set_password(new_password)
            user.save()
            return HttpResponse('Zmiana hasła')
        else:
            return render(request, 'app_recipe/form.html', {'form': form})

app_recipe/templates/app_recipe/add_recipe.html
{% extends 'app_recipe/index.html' %}
{{ form.non_field_errors }}

{% load crispy_forms_tags %}

{% block content %}

    <br>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
{#        {{ form.as_p }}#}

{#      const fields #}
        <div class="constant_block">
            <div>
                {{ form.recipe_name.errors }}
                <label for="{{ form.recipe_name.id_for_label }}">Nazwa:</label>
                {{ form.recipe_name }}
            </div>
            <br>
            <div>
                {{ form.main_image.errors }}
                <label for="{{ form.main_image.id_for_label }}">Obrazek główny:</label>
                {{ form.main_image }}
            </div>
            <br>
            <div>
                {{ form.cooking_time.errors }}
                <label for="{{ form.cooking_time.id_for_label }}">Czas wykonania:</label>
                <input type="time" name="cooking_time" id="cooking_time">
            </div>
            <br>
            <div>
                {{ form.number_of_persons.errors }}
                <label for="{{ form.number_of_persons.id_for_label }}">Dla ilu osób:</label>
                {{ form.number_of_persons }}
            </div>
            <br>
        </div>

{#      ingredients #}
        <div class="recipe_name">Składniki</div>
        <div class="ingredients_block">

            <div>
                {{ form.ingredients.errors }}
                <label for="{{ form.ingredients.id_for_label }}"></label>
                {{ form.ingredients }}

                {{ form.quantity.errors }}
                <label for="{{ form.quantity.id_for_label }}">ilość:</label>
                {{ form.quantity }}

                {{ form.units.errors }}
                <label for="{{ form.units.id_for_label }}">jednostka:</label>
                {{ form.units }}
            </div>

        </div>

        <br>

        <div class="ingredient_buttons">
            <button id="add_field_ingredient">+ dodaj składnik</button>
            <button id="del_field_ingredient">- usuń składnik</button>
        </div>
        <br>

        {#      steps block#}
        <div class="steps_block">
            <div>
                <div class="recipe_name">Krok 1</div>
                {{ form.step_description.errors }}
                <label for="{{ form.step_description.id_for_label }}">Opis:</label>
                {{ form.step_description }}

                <br>

                {{ form.step_image.errors }}
                <label for="{{ form.step_image.id_for_label }}">Obraz bieżącego kroku:</label>
                {{ form.step_image }}

            </div>
        </div>

        <div class="step_buttons">
            <button id="add_next_step">+ dodaj krok</button>
            <button id="del_prev_step">- usuń krok</button>
        </div>


        <br>
        <input type="submit" value="{{submit_value|default:'OK'}}">
    </form>
    <br>
    <br>
    <br>

{% endblock %}

app_recipe/templates/app_recipe/empty.html
<tr>
    <th>
        <label for="id_recipe_name">Name:</label>
    </th>
    <td>
        <input type="text" name="recipe_name" maxlength="128" id="id_recipe_name" required>
    </td>
</tr>

<tr>
    <th>
        <label for="id_cooking_time">Cooking time:</label>
    </th>
    <td>
        <input type="text" name="cooking_time" id="id_cooking_time" required>
    </td>
</tr>
<tr>
    <th><
        label for="id_number_of_persons">Number of persons:</label>
    </th>
    <td>
        <input type="number" name="number_of_persons" id="id_number_of_persons" required>
    </td>
</tr>
<tr>
    <th>
        <label for="id_ingredients">Ingredients:</label>
    </th>
    <td>
        <select name="ingredients" id="id_ingredients">
            <option value="mąka pszenna">mąka pszenna</option>
            <option value="woda">woda</option>
            <option value="jajo (kurze)">jajo (kurze)</option>
        </select>
    </td>
</tr>

<tr>
    <th>
        <label for="id_quantity">Quantity:</label>
    </th>
    <td>
        <input type="number" name="quantity" step="0.01" min="0.01" id="id_quantity" required>
    </td>
</tr>

<tr>
    <th>
        <label for="id_units">Units:</label>
    </th>
    <td>
        <select name="units" id="id_units">
          <option value="łyżka stołowa">łyżka stołowa</option>
          <option value="szklanka">szklanka</option>
          <option value="łyżeczka">łyżeczka</option>
        </select>
    </td>
</tr>

app_recipe/templates/app_recipe/form.html
{% extends 'app_recipe/index.html' %}

{% load crispy_forms_tags %}

{% block content %}
    <div>{{ info }}</div>
    <div class="form-container">
    <form method="post" >
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="{{submit_value|default:'OK'}}">
    </form>
    </div>

{% endblock %}

app_recipe/templates/app_recipe/index.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Przepisy</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
    <script type="text/JavaScript" src="{% static 'app_recipe/js/app_recipe.js' %}"></script>
    <link rel="stylesheet" href="{% static 'app_recipe/styles/styles.css' %}">
</head>
<body style="position: relative; min-height: 100vh" class="body-main">

    {% block head %}

        {% if user.is_authenticated %}
            <table width="100%">
                <tr>
                    <td rowspan="2" width="20%"><a href="{% url 'index' %}"><img src="{% static 'app_recipe/imgs/icon.jpeg' %}" height="80"></a></td>
                    <td align="center"><a href="{% url 'index' %}"> Moje przepisy </a></td>  {#link does not support yet#}
                    <td align="right" width="15%"><a>Witaj {{ user }}!</a></td>
                </tr>
                <tr>
                    <td align="center"><a href="{% url 'add_recipe' %}"> Dodaj nowy przepis </a></td>
                    <td align="right" width="15%"><a href="{% url 'logout' %}"> Logout </a></td>
                </tr>
            </table>

        {% else %}
            <table>
                <tr>
                    <td rowspan="2" width="20%"><a href="{% url 'index' %}"><img src="{% static 'app_recipe/imgs/icon.jpeg' %}" height="80"></a></td>
                    <td rowspan="2" align="center">
                        <img src="{% static 'app_recipe/imgs/main-coocking.jpg' %}" width="500">
                    </td>
                    <td align="right" width="15%"><a href="{% url 'login' %}"> Login </a></td>
                </tr>
                <tr>
                    <td align="right" width="15%"><a href="{% url 'add_user' %}"> Sign in </a></td>
                </tr>
            </table>
        {% endif %}

    {% endblock %}


    {% block search %}
        <form class="form-wrapper" id="searchbar">
            <input type="text" id="search1" placeholder="Znajdź przepis ..." required>
            <input type="text" id="search2" placeholder="Kategoria ..." required>
            <input type="text" id="search3" placeholder="Kuchnie świata ..." required>
            <input type="submit" value="Szukaj" id="submit">
        </form>
        <br>
        <br>
    {% endblock %}


    {% block content %}
        {% for recipe in recipes %}
        <table width="100%" border="1" >
            <tr>
                <td rowspan="3" align="center" width="40%" height="20%">
                    <a href="recipe/{{ recipe.pk }}">
                        <img src="/media/{{ recipe.main_image }}" alt="main_photo" width="70%">
                    </a>
                </td>
                <td align="center" class="recipe_name">{{ recipe.recipe_name }}</td>
            </tr>

            <tr>

                <td>
                    <ul>
                        {% for ingredient in recipe.ingredients.all %}
                            <li>{{ ingredient.ingredient_name }}</li>
                        {% endfor %}
                    </ul>
                </td>
            </tr>

            <tr>

                <td align="center">
                    <img src="{% static 'app_recipe/imgs/like.png' %}" alt="like" width="20">
                    <a class="like">{{ recipe.pk|add:'320' }}</a>
                    <a>||</a>
                    <img src="{% static 'app_recipe/imgs/time.png' %}" alt="like" width="15">
                    <a class="like">{{ recipe.pk|add:'15' }} min</a>
                </td>
            </tr>
        </table>
            <br>
        {% endfor %}
        <br>
        <br>
    {% endblock %}


    {% block footer %}
        <div id="footer" align="center">
            <a>created with support</a>
            <img src="{% static 'app_recipe/imgs/cl.jpg' %}" height="18">
        </div>
    {% endblock %}

</body>
</html>

app_recipe/templates/app_recipe/ingredient_form.html
{#{% extends 'recipe/base.html' %}#}

<form action="" method="post">
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Save">
</form>

app_recipe/templates/app_recipe/recipe_by_id.html
{% extends 'app_recipe/index.html' %}

{% load crispy_forms_tags %}

{% block content %}

    <h2>{{ recipe_obj.recipe_name }}</h2>
{#    <div>Czas gotowania: {{ recipe_obj.cooking_time }} </div>#}
    <div>Czas gotowania: 20 min </div>

    <table>
        <tr>
            <td>
                <img src="/media/{{ recipe_obj.main_image }}" alt="main_photo" height="200">
            </td>

            <td>
                <ul>
                    <a class="recipe_name">Składniki</a>
                    {% for ingredient in recipe_obj.recipeingredientquantityunit_set.all %}
                         <li>{{ingredient.ingredient.ingredient_name}} - {{ingredient.quantity}} ({{ingredient.unit.unit_name}})</li>
                    {% endfor %}
                </ul>
            </td>
        </tr>
    </table>






    {% for step in recipe_obj.step_set.all|dictsort:"pk" %}
        <table width="100%">
            <tr>
                <td>
                    <div class="recipe_name">Krok {{ forloop.counter }}</div>
                    <p>{{ step.description }}</p>
                </td>
                <td align="right">
                    <img src="/media/{{ step.step_image }}" alt="step_photo" height="100">
                </td>
            </tr>
        </table>
    {% endfor %}
    <br>
    <br>
{% endblock %}

app_recipe/templates/app_recipe/unit_form.html
{#{% extends 'app_recipe/index.html' %}#}

<form action="" method="post">
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Save">
</form>